# Este workflow utiliza ações que não são certificadas pelo GitHub.
# Elas são fornecidas por terceiros e regidas por termos de serviço específicos.

# Este workflow aciona uma análise do SonarCloud para identificar vulnerabilidades e bugs.
# Os resultados serão enviados para o painel do SonarCloud.

# Passos para configurar:
# 1. Garanta que o projeto esteja importado no SonarCloud.
# 2. Configure os segredos no GitHub (Settings > Secrets):
#    - SONAR_TOKEN: Token gerado no SonarCloud.
#    - SONAR_HOST_URL: https://sonarcloud.io

name: Análise SonarQube

# Define quando o workflow será executado
on:
  push:
    branches: ["main"] # Executa ao enviar código para a branch main
  pull_request:
    branches: ["main"] # Executa ao abrir ou atualizar um Pull Request para a main
  workflow_dispatch: # Permite execução manual pela interface do GitHub

permissions:
  pull-requests: read # Permite que o SonarQube leia informações de PRs para comentários

jobs:
  Analysis:
    name: Execução da Análise Estática
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # O Sonar precisa do histórico completo para análise precisa de autoria (git blame)

      - name: Analisar com SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático do GitHub para integração
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token de autenticação do SonarCloud
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # URL do servidor (https://sonarcloud.io)
        with:
          args: >
            -Dsonar.organization=edugomess
            -Dsonar.projectKey=edugomess_Asset-Management
            -Dsonar.sources=.
            -Dsonar.verbose=false
